name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o slack-review-notify-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o slack-review-notify-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o slack-review-notify-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o slack-review-notify-windows-amd64.exe

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            slack-review-notify-linux-amd64
            slack-review-notify-darwin-amd64
            slack-review-notify-darwin-arm64
            slack-review-notify-windows-amd64.exe
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Extract tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.TAG_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
